### PR TITLE
#166000116 Fix parent info on the comments

### PR DESCRIPTION
**Pull request by Amoswachira**
### What does this PR do?
- Fixes the error message 
- Adds parent information on the comments
### What are the tasks to be completed?
```
GET /api/articles/{slug}/comments/
GET /api/articles/{slug}/comments/id/

```

* Fix that user can be able get to multiple and single comments where the response data and message are properly fixed.

### How can this be manually tested?
 **After cloning the repo:-**
**Test with postman**
Sign up a user, login, grub the token and add it to authorization:
```
$ git checkout  bg-fix-parent-comment-info-166000116  
$ python manage.py runserver
```
**To run tests on terminal**
```
$ python manage.py test authors/apps/articles
```

### What are the relevant pivotal tracker stories?
[#166000116](https://www.pivotaltracker.com/n/projects/2326460/stories/166000116)

### Screenshots
Screenshot 2019-05-14 at 16 59 43
Screenshot 2019-05-14 at 16 58 46

### CODE REVIEW

**Review by Ogutu-Brian — APPROVED** [review]
LGTM

**Comment by oluwagbenga-joloko** [comment]
The parent key on the comment replies should be renamed to `parent_id`.

**Review by IssaIan — APPROVED** [review]
LGTM

**Review by matthenge — APPROVED** [review]
LGTM

**Comment by Amoswachira** [comment]
@oluwagbenga-joloko let me change that

**Comment by Amoswachira** [comment]
@oluwagbenga-joloko I have resolved the issue

**Pull request merged**
