### PR TITLE
#165305754  Add descriptive signup validation errors 

### PR DESCRIPTION
**Pull request by mdn-network**
#### Description
Seeks to merge the Heroku integration to develop branch to enable other users to access and use the live application.

#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [x] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [ ] End to end
- [ ] Integration

#### Checklist:
- [ ] My code follows the style guide for this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

#### Pivotal Tracker
[165305754](https://www.pivotaltracker.com/story/show/165305754)

### CODE REVIEW

**Review by a-braham — CHANGES_REQUESTED** [review]
@Philipotieno You could change the heading of the PR to follow the Andela Playbook convention.

**Comment by mdn-network** [comment]
@a-braham Just changed that

**Review by IssaIan — APPROVED** [review]
LGTM

**Review by a-braham — APPROVED** [review]
LGTM

**Review by Ogutu-Brian — APPROVED** [review]
LGTM

**Review by Amoswachira — APPROVED** [review]
LGTM

**Review by Ogutu-Brian — COMMENTED** [review]
Hello @Philipotieno ,
Instead of the many regular expressions used here,
You can consider using a password validator and an email validator from Django.
```
django.core.validators.EmailValidator
django.contrib.auth.password_validation.validate_password
```
Both of them raise Validation error (from django.core.exceptions.ValidationError) that are a list of the errors that occur. I think this would improve the code quality on our code base.

**Review by matthenge — APPROVED** [review]
LGTM

**Pull request merged**
