### PR TITLE
#165305763 Users should be able to follow each other

### PR DESCRIPTION
**Pull request by Amoswachira**
#### Description
users should be able to follow and or unfollow other authors. 

#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [x] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [ ] End to end test
- [ ]  Integration test
- [x]  Unit test

#### Checklist:
- [x] My code follows the style guide for this project
- [ ] I have linted my code prior to submission
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

#### Pivotal Tracker
[#165305763)](https://www.pivotaltracker.com/n/projects/2326460/stories/165305763)

#### Screenshots
screencapture-127-0-0-1-8000-api-swagger-2019-05-02-08_19_14

### CODE REVIEW

**Review by a-braham — COMMENTED** [review]
Try to increase your test coverage

**Comment by Amoswachira** [comment]
@a-braham let me add some tests

**Review by a-braham — COMMENTED** [review]
you could add the following field, as stated on the readme file

**Review by Ogutu-Brian — CHANGES_REQUESTED** [review]
Hello @Amoswachira ,
Use this [Link of your coveralls report](https://coveralls.io/builds/23141413/source?filename=authors/apps/profiles/views.py) to check the sections of your code that are not tested. The sections are highlighted in red.

**Comment by Amoswachira** [comment]
@Ogutu-Brian thank you that is the task I am completing as we speak

**Comment by Amoswachira** [comment]
@Ogutu-Brian I have added the missing tests

**Review by a-braham — APPROVED** [review]
LGTM

**Review by matthenge — APPROVED** [review]
LGTM

**Review by Ogutu-Brian — APPROVED** [review]
LGTM

**Pull request merged**
