### PR TITLE
#165305743 Upgrade django to version 2.1

### PR DESCRIPTION
**Pull request by Amoswachira**
#### Description
Upgrade django form version 1.10  to  django version 2.1

#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [ ] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [ ] End to end
- [ ] Integration

#### Checklist:
- [ ] My code follows the style guide for this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

#### Pivotal Tracker
[165305743](https://www.pivotaltracker.com/n/projects/2326460/stories/165305743)

### CODE REVIEW

**Review by Ogutu-Brian — APPROVED** [review]
LGTM

**Review by matthenge — APPROVED** [review]

**Review by IssaIan — COMMENTED** [review]
You have added some unnecessary requirements to our file eg. powerline-status. Please check what dependencies you have in your virtual environment before freezing them onto the requirements.txt file.

**Comment by Amoswachira** [comment]
@IssaIan thankyou for the feedback let me work on that

**Comment by Amoswachira** [comment]
@IssaIan I have made the changes.

**Review by IssaIan — APPROVED** [review]
LGTM

**Pull request merged**
