### PR TITLE
#165835216 Validate Password During Password Reset

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
- Validates repeated patterns and password sequences during password reset
### What are the tasks to be completed?
* Ensure a user cannot use a repeated pattern or sequence for a password
### How can this be manually tested?
a. **After cloning the repo:-**
```
$ git checkout  bg-password-reset-validation-165835216
$ python manage.py runserver
```
b. **Test with postman**
1. After signing up a user, send a password reset link to user:
```
POST /api/users/password/reset/
{
    "email":"your email address"
}
```
b. **Click on the verification link sent to the email to reset password**

### What are the relevant pivotal tracker stories?
[#165835216](https://www.pivotaltracker.com/story/show/165835216)

### CODE REVIEW

**Review by a-braham — APPROVED** [review]
LGTM

**Review by mdn-network — APPROVED** [review]
LGTM

**Review by matthenge — CHANGES_REQUESTED** [review]
Please fix the test coverage

**Comment by Ogutu-Brian** [comment]
> Please fix the test coverage

I have fixed the tests @matthenge

**Comment by Ogutu-Brian** [comment]
> Please fix the test coverage

Hello @matthenge ,
I have fixed that

**Review by matthenge — APPROVED** [review]
LGTM

**Review by IssaIan — APPROVED** [review]
LGTM

**Pull request merged**
